import "./globals.css";
import RainbowKitAndWagmiProvider from "./providers/RainbowKitAndWagmiProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <RainbowKitAndWagmiProvider>{children}</RainbowKitAndWagmiProvider>
      </body>
    </html>
  );
}
